### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by garammasala29** [garammasala29/NursePicks#2]
draw.ioで作成
プラクティスの提出物

**Comment by garammasala29** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/69446373/169441636-fc548037-4f10-42d7-b1d1-da2c955cea22.png">

- Users
SNS認証を使用するため`provider`と`uid`を持たせています。SNS認証から`icon_url`を取得します。

- Posts
postされたurlからmeta情報(`post_name`/`site_name`/`image_url`)を取得します

**Comment by komagata** [comment]
いいと思います〜！

**Comment by garammasala29** [comment]
確認いただいたのでclose
