### ISSUE TITLE
URL設計

### ISSUE THREAD

**Issue by garammasala29** [garammasala29/NursePicks#3]
プラクティスにあり

**Comment by garammasala29** [comment]
| Method | Path | Discription |
| --- | --- | --- |
|GET|/|トップページ、記事一覧、サービス説明|
|GET|/posts/new|記事の投稿ページ|
|POST|/posts|記事の登録|
|GET|/posts/:id|idの記事とコメントを表示|
|DELETE|/posts/:id|idの記事を削除|
|POST|/posts/comments|コメントの登録|
|DELETE|/posts/comments/:id|コメント削除|
|POST|/posts/:id/likes|いいねの登録|
|DELETE|/posts/:id/likes|いいね削除|
| | |
|GET|/users/:id|ユーザー詳細、ユーザーの投稿/コメント/いいねがみれる|
|GET|/users/new|ユーザー作成ページ(SNS認証を終えた後にとぶ)|
|GET|/users/:id/edit|ユーザー情報編集ページ|
|PUT|/users/:id|ユーザー情報更新|
| | |
|GET|/signup|アカウント登録ページ|
|GET|/login|ログインページ|

記事とコメントは編集機能はつけず、登録と削除のみの仕様としています。
ユーザーの認証周りはdevise gemを使います。

**Comment by garammasala29** [comment]
ご確認ありがとうございます！
- コメントの登録・削除のpathを変更しました
- signupとsigninに統一しました
- ユーザー編集は`/current_user/edit`としました

| Method | Path | Discription |
| --- | --- | --- |
|GET|/|トップページ、記事一覧、サービス説明|
|GET|/posts/new|記事の投稿ページ|
|POST|/posts|記事の登録|
|GET|/posts/:id|idの記事とコメントを表示|
|DELETE|/posts/:id|idの記事を削除|
|POST|/posts/:id/comments|コメントの登録|
|DELETE|/posts/:id/comments/:id|コメント削除|
|POST|/posts/:id/likes|いいねの登録|
|DELETE|/posts/:id/likes|いいね削除|
| | |
|GET|/users/:id|ユーザー詳細、ユーザーの投稿/コメント/いいねがみれる|
|GET|/users/new|ユーザー作成ページ(SNS認証を終えた後にとぶ)|
|GET|/current_user/edit|ユーザー情報編集ページ|
|PUT|/users/:id|ユーザー情報更新|
| | |
|GET|/signup|アカウント登録ページ|
|GET|/signin|ログインページ|

**Comment by garammasala29** [comment]
@komagata さん
bootcampの方でしかメンションを飛ばしていませんでした💦
こちら再度ご確認よろしくお願いします！

**Comment by komagata** [comment]
確認させて頂きました。OKです〜🙆‍♂️

**Comment by garammasala29** [comment]
ありがとうございました！こちらで進めていきます！
こちらのissueはcloseします。
